import { Item } from "./types";

export const items: Item[] = [
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
  { name: "Matéria exemplo", hours: 30 },
];
